<%
  platforms = %w(centos-7 centos-6)
  use_git = true
%>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  sudo: true

platforms:
<% platforms.each do |plat| %>
- name: <%= plat %>
  verifier:
      inspec_tests:
      - name: <%= plat %>
      <% if use_git == false %>
        path: test/integration/<%= plat %>/inspec
      <% else %>
        url: https://github.com/jburns12/inspec_profiles/tree/master_original/profiles/disa_stig-rhel7-baseline
      <% end %>
<% end %>

suites:
  - name: default
    run_list:
      - recipe[auditd]
      - recipe[stig::auditd]
      - recipe[stig::auditd_rules]
      - recipe[stig::fstab_tmp]
      - recipe[stig::tcp_wrappers]
      - recipe[stig::boot_settings]
      - recipe[stig::proc_hard]
      - recipe[stig::cis]
      - recipe[stig::avahi_daemon]
      - recipe[stig::ipv6]
      - recipe[stig::dhcp]
      - recipe[stig::mail_transfer_agent]
      - recipe[stig::hosts]
      - recipe[stig::rsyslog]
      - recipe[logrotate::global]
      - recipe[stig::sshd_config]
      - recipe[stig::system_auth]
      - recipe[stig::login_defs]
      - recipe[stig::login_banner]
      - recipe[stig::file_permissions]
      - recipe[stig::audits]
      - recipe[stig::audit_scripts]
      - recipe[stig::su_restriction]
      - recipe[stig::aide]
    attributes:
      "auditd" :
        "ruleset" : "stig"
