<%
  platforms = %w(centos-7 centos-6)
  use_git = true
%>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  root_path: /home/vagrant/kitchen

verifier:
  name: inspec
  sudo: true
  sudo_options: '-u root'
  format: json
  output: hardenedrhel7.json
  attrs:
    - attributes.dev.yml

platforms:
<% platforms.each do |plat| %>
- name: <%= plat %>
  verifier:
    inspec_tests:
      - name: <%= plat %>
      <% if use_git == false %>
        path: ../../auditd_rules_test/inspec_profiles/profiles/disa_stig-rhel7-baseline
      <% else %>
        git: https://github.com/djhaynes/inspec-profile-disa_stig-el7
        branch: dev
      <% end %>
<% end %>

suites:
  - name: default
    run_list:
      - recipe[stig::yum]
      - recipe[stig::yum_update]
      - recipe[stig::add_packages]
      - recipe[auditd]
      - recipe[stig::auditd]
      - recipe[stig::auditd_rules]
      - recipe[stig::fstab_tmp]
      - recipe[stig::tcp_wrappers]
      - recipe[stig::boot_settings]
      - recipe[stig::proc_hard]
      - recipe[stig::cis]
      - recipe[stig::avahi_daemon]
      - recipe[stig::ipv6]
      - recipe[stig::dhcp]
      - recipe[stig::mail_transfer_agent]
      - recipe[stig::hosts]
      - recipe[stig::rsyslog]
      - recipe[logrotate::global]
      - recipe[stig::sshd_config]
      - recipe[stig::system_auth]
      - recipe[stig::login_defs]
      - recipe[stig::login_banner]
      - recipe[stig::file_permissions]
      - recipe[stig::audits]
      # - recipe[stig::audit_scripts]
      - recipe[stig::su_restriction]
      - recipe[stig::aide]
      - recipe[stig::local_users]
    attributes:
      "auditd" :
        "ruleset" : "stig"
