source 'https://rubygems.org'
gem 'berkshelf'
gem 'chefspec'
gem 'foodcritic'
gem 'inspec', '>= 1.39.1'
gem 'kitchen-inspec'
gem 'kitchen-vagrant'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'serverspec'
gem 'stove'
gem 'test-kitchen'
